#!/usr/bin/env bash
set -u

pepew_miner_dir() {
  if [[ -n "${MINER_DIR:-}" && -d "${MINER_DIR}" ]]; then
    printf '%s' "${MINER_DIR}"
  else
    cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
  fi
}

miner_ver() {
  printf '%s\n' "${CUSTOM_VERSION:-1.0.3}"
}

miner_config_gen() {
  local miner_dir conf_file setup_file diagnostic_log proxy_log proxy_port
  local pool user pass extra_raw tmp_conf
  local -a args extra

  miner_dir="$(pepew_miner_dir)"
  conf_file="${CUSTOM_CONFIG_FILENAME:-${miner_dir}/config.txt}"
  setup_file="${miner_dir}/setup.txt"
  diagnostic_log="${miner_dir}/pepepow-debug.log"
  proxy_log="/var/log/miner/custom/PepeW-Miner-v1.0.3-HiveOS/stratum-proxy.log"
  proxy_port="${PEPEPOW_PROXY_PORT:-49333}"

  # miner-run already sources wallet.conf. Source it only for direct/manual tests.
  if [[ -z "${CUSTOM_URL:-}" && -r /hive-config/wallet.conf ]]; then
    # shellcheck disable=SC1091
    source /hive-config/wallet.conf
  fi

  pool="${CUSTOM_URL:-}"
  user="${CUSTOM_TEMPLATE:-}"
  pass="${CUSTOM_PASS:-x}"
  extra_raw="${CUSTOM_USER_CONFIG:-}"

  if [[ -z "${pool}" ]]; then
    echo "HiveOS pool URL is missing (CUSTOM_URL)" >&2
    return 1
  fi
  if [[ -z "${user}" ]]; then
    echo "HiveOS wallet/template is missing (CUSTOM_TEMPLATE)" >&2
    return 1
  fi
  if [[ ! "${proxy_port}" =~ ^[0-9]+$ ]] || (( proxy_port < 1024 || proxy_port > 65535 )); then
    echo "Invalid PEPEPOW_PROXY_PORT: ${proxy_port}" >&2
    return 1
  fi

  args=("-o" "stratum+tcp://127.0.0.1:${proxy_port}"
        "-u" "${user}" "-p" "${pass}"
        "--diagnostic-log" "${diagnostic_log}")

  if [[ "${PEPEW_DIAGNOSTIC:-0}" == "1" ]]; then
    args+=("--diagnostic")
  fi

  if [[ -n "${extra_raw}" ]]; then
    # HiveOS exposes this as an expert field. Preserve quoted argument groups.
    eval "extra=( ${extra_raw} )"
    args+=("${extra[@]}")
  fi

  mkdir -p "${miner_dir}" "$(dirname "${proxy_log}")"
  tmp_conf="${conf_file}.tmp.$$"
  {
    echo "# Generated by PepeW Miner HiveOS integration"
    printf 'PEPEPOW_ARGS=('
    printf ' %q' "${args[@]}"
    echo ' )'
    printf 'PEPEPOW_UPSTREAM=%q\n' "${pool}"
    printf 'PEPEPOW_PROXY_LOG=%q\n' "${proxy_log}"
    printf 'PEPEPOW_PROXY_PORT=%q\n' "${proxy_port}"
  } > "${tmp_conf}"
  chmod 600 "${tmp_conf}"
  mv -f "${tmp_conf}" "${conf_file}"

  {
    echo "Miner: ${CUSTOM_NAME:-PepeW-Miner-v1.0.3-HiveOS}"
    echo "Version: $(miner_ver)"
    echo "Directory: ${miner_dir}"
    echo "Upstream pool: configured"
    echo "Wallet/template: configured"
    echo "Password: configured"
    echo "Local proxy: stratum+tcp://127.0.0.1:${proxy_port}"
    echo "Extra arguments: ${extra_raw:+configured}"
    echo "Status file: ${miner_dir}/miner-status.env"
  } > "${setup_file}"
}

miner_config_echo() {
  local miner_dir setup_file
  miner_dir="$(pepew_miner_dir)"
  setup_file="${miner_dir}/setup.txt"
  if [[ -r "${setup_file}" ]]; then
    cat "${setup_file}"
  else
    echo "PepeW Miner configuration has not been generated yet"
  fi
}
