#!/usr/bin/env bash
set -u

if [[ -r /hive-config/wallet.conf ]]; then
  # shellcheck disable=SC1091
  source /hive-config/wallet.conf
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
miner_dir="${script_dir}"
conf_file="${miner_dir}/config.txt"
setup_file="${miner_dir}/setup.txt"
diagnostic_log="${miner_dir}/pepepow-debug.log"
proxy_log="${miner_dir}/stratum-proxy.log"
proxy_port="${PEPEPOW_PROXY_PORT:-49333}"

pool="${CUSTOM_URL:-}"
user="${CUSTOM_TEMPLATE:-}"
pass="${CUSTOM_PASS:-x}"
extra_raw="${CUSTOM_USER_CONFIG:-}"

if [[ -z "${pool}" ]]; then
  echo "HiveOS pool URL is missing (CUSTOM_URL)" >&2
  return 1 2>/dev/null || exit 1
fi
if [[ -z "${user}" ]]; then
  echo "HiveOS wallet/template is missing (CUSTOM_TEMPLATE)" >&2
  return 1 2>/dev/null || exit 1
fi

# The binary always derives miner-status.env from --diagnostic-log. Keep that
# path inside the package even when verbose per-job diagnostics are disabled.
args=("-o" "stratum+tcp://127.0.0.1:${proxy_port}" "-u" "${user}" "-p" "${pass}"
      "--diagnostic-log" "${diagnostic_log}")

# Full per-job diagnostics are optional because they add disk and console I/O.
if [[ "${PEPEW_DIAGNOSTIC:-0}" == "1" ]]; then
  args+=("--diagnostic")
fi

if [[ -n "${extra_raw}" ]]; then
  eval "extra=( ${extra_raw} )"
  args+=("${extra[@]}")
fi

mkdir -p "${miner_dir}"
{
  echo "# Generated by HiveOS h-config.sh"
  printf 'PEPEPOW_ARGS=('
  printf ' %q' "${args[@]}"
  echo ' )'
  printf 'PEPEPOW_UPSTREAM=%q\n' "${pool}"
  printf 'PEPEPOW_PROXY_LOG=%q\n' "${proxy_log}"
  printf 'PEPEPOW_PROXY_PORT=%q\n' "${proxy_port}"
} > "${conf_file}"

{
  echo "Miner directory: ${miner_dir}"
  echo "Upstream pool: configured via HiveOS"
  echo "Local proxy: stratum+tcp://127.0.0.1:${proxy_port}"
  echo "User: configured via HiveOS"
  echo "Password: configured via HiveOS"
  echo "Extra config: ${extra_raw:+configured}"
  echo "Compatibility --pepepow injection: disabled"
  echo "Proxy submit rewriting: disabled"
  echo "Pool reference: matrix_seed=BLAKE3(masked_header), header_nonce=BE32, mix_nonce=LE32, submit_nonce=LE_HEX"
  echo "Diagnostic mode: ${PEPEW_DIAGNOSTIC:-0}"
  echo "Diagnostic/status path: ${diagnostic_log}"
  echo "Proxy log: ${proxy_log}"
  echo "Final miner command: ./pepepowminer [credentials supplied by HiveOS]"
} > "${setup_file}"

export PEPEPOW_CONFIG_FILE="${conf_file}"
