CUSTOM_NAME=PepeW-Miner-v1.0.3-HiveOS
CUSTOM_VERSION=1.0.3
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/PepeW-Miner-v1.0.3-HiveOS/config.txt
CUSTOM_LOG_BASENAME=/var/log/miner/custom/PepeW-Miner-v1.0.3-HiveOS/pepew
MINER_NAME=$CUSTOM_NAME
MINER_VERSION=$CUSTOM_VERSION
MINER_CONFIG_FILENAME=$CUSTOM_CONFIG_FILENAME
MINER_LOG_BASENAME=$CUSTOM_LOG_BASENAME
MINER_API_PORT=4049
