CUSTOM_NAME=pepepowminer
CUSTOM_VERSION=0.6.0-PR
MINER_NAME=$CUSTOM_NAME
MINER_VERSION=$CUSTOM_VERSION
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/pepepowminer-v0.6.0-PR/config.txt
MINER_CONFIG_FILENAME=$CUSTOM_CONFIG_FILENAME
CUSTOM_LOG_BASENAME=/var/log/miner/custom/$CUSTOM_NAME
MINER_API_PORT=4049
