CUSTOM_NAME=PepeW-Miner
CUSTOM_VERSION="v1.0.5 V100 Beta"
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/PepeW-Miner/config.txt
CUSTOM_LOG_BASENAME=/var/log/miner/custom/PepeW-Miner/pepew
MINER_NAME=$CUSTOM_NAME
MINER_VERSION=$CUSTOM_VERSION
MINER_CONFIG_FILENAME=$CUSTOM_CONFIG_FILENAME
MINER_LOG_BASENAME=$CUSTOM_LOG_BASENAME
MINER_API_PORT=4049
