#!/usr/bin/env bash
set -euo pipefail

cd "${MINER_DIR:-$(dirname "$0")}" 
conf_file="${CUSTOM_CONFIG_FILENAME:-${MINER_DIR:-.}/config.txt}"

if [[ ! -x ./pepepowminer ]]; then
  echo "pepepowminer binary is missing or not executable" >&2
  exit 1
fi
if [[ ! -s "${conf_file}" ]]; then
  echo "HiveOS miner config is missing: ${conf_file}" >&2
  exit 1
fi

# The config is generated by h-config.sh using shell-escaped arguments.
# shellcheck disable=SC1090
args=$(cat "${conf_file}")
eval "exec ./pepepowminer ${args}"
