#!/usr/bin/env bash
set -o pipefail
LOG="${1:-/root/v081-coldpath.log}"
REFRESH="${REFRESH:-10}"
SCREEN_NAME="${SCREEN_NAME:-v081-coldpath}"
IDS=(baseline selector-inline selector-combined selector-noinline selector-coldcall combined-noinline combined-coldcall combined-coldcall-t64-b1 combined-coldcall-t128-b1)
TITLES=("Контроль v0.6.0" "Победитель v0.8.0 exact selector" "Единый декодер one/two" "Outlined safe_nonlinear" "Outlined полный cold contribution" "Единый декодер + outlined nonlinear" "Единый декодер + cold contribution" "Cold contribution, launch bound 1" "Cold contribution, 128 потоков")
TOTAL="${#IDS[@]}"

bar(){ local d="${1:-0}" t="${2:-1}" w="${3:-42}" f e; [[ "$d" =~ ^[0-9]+$ ]]||d=0; [[ "$t" =~ ^[1-9][0-9]*$ ]]||t=1; ((d>t))&&d=$t; f=$((d*w/t));e=$((w-f));printf '[';printf '%*s' "$f" ''|tr ' ' '#';printf '%*s' "$e" ''|tr ' ' '-';printf ']'; }
field(){ local l="${1:-}" k="${2:-}" x;for x in $l;do [[ ${x%%=*} == "$k" ]]&&{ echo "${x#*=}";return;};done;return 1; }
index(){ local p="${1:-}" i;for ((i=0;i<TOTAL;i++));do [[ ${IDS[$i]} == "$p" ]]&&{ echo $((i+1));return;};done;echo 0; }
result(){ grep -a '^PROFILE_RESULT ' "$LOG" 2>/dev/null|grep " profile=$1 "|tail -1||true; }

while true;do
 printf '\033[H\033[2J';echo '================================================================================';echo ' PEPEPOW v0.8.1 — COLD-PATH OUTLINING + COMBINED SELECTOR';echo ' Цель: снять регистровое давление редкой nonlinear-ветки и приблизиться к 2 MH/s';echo '================================================================================';echo
 [[ -f $LOG ]]||{ echo "Журнал ещё не создан: $LOG";sleep "$REFRESH";continue; }
 completed=$(grep -ac '^PROFILE_RESULT ' "$LOG" 2>/dev/null||true);valid=$(grep -a '^PROFILE_RESULT ' "$LOG"|grep -c ' valid=1 '||true);failed=$(grep -a '^PROFILE_RESULT ' "$LOG"|grep -c ' valid=0 '||true);current=$(grep -a '^PROFILE=' "$LOG"|tail -1|cut -d= -f2-);status=$(grep -a '^STATUS=' "$LOG"|tail -1|cut -d= -f2-);config=$(grep -a '^PROFILE_CONFIG ' "$LOG"|tail -1);[[ -n $current ]]||current=инициализация;[[ -n $status ]]||status=ПОДГОТОВКА
 if screen -ls 2>/dev/null|grep -q "\.$SCREEN_NAME[[:space:]]";then state=РАБОТАЕТ;elif grep -aq 'V0.8.1 COLD-PATH MATRIX COMPLETE' "$LOG";then state=ЗАВЕРШЁН;completed=$TOTAL;else state='ОСТАНОВЛЕН / ПРОВЕРЬТЕ ЖУРНАЛ';fi
 echo 'ОБЩИЙ СТАТУС';echo '--------------------------------------------------------------------------------';echo "Состояние:          $state";echo "Профилей:           $TOTAL";echo "Завершено:          $completed из $TOTAL (валидных $valid, ошибок $failed)";printf 'Общий прогресс:     ';bar "$completed" "$TOTAL";printf ' %d%%\n' "$((completed*100/TOTAL))";echo "Обновление:         каждые $REFRESH секунд";echo
 ci=$(index "$current");echo 'ТЕКУЩИЙ ПРОФИЛЬ';echo '--------------------------------------------------------------------------------';if ((ci>0));then echo "Профиль:            $ci из $TOTAL — $current";echo "Гипотеза:           ${TITLES[$((ci-1))]}";else echo "Профиль:            $current";fi;echo "Этап:               $status";[[ -n $config ]]&&echo "Конфигурация:       ${config#PROFILE_CONFIG }"
 last=$(grep -a '^BENCH_RUN ' "$LOG"|grep " profile=$current "|tail -1||true);if [[ -n $last ]];then rt=$(field "$last" run);h=$(field "$last" hps);r=$((10#${rt%%/*}));tt=$((10#${rt##*/}));echo "Benchmark:          $r из $tt";printf 'Прогресс benchmark: ';bar "$r" "$tt";printf '\n';echo "Последний хеш:      $(awk -v h="$h" 'BEGIN{printf "%.6f",h/1e6}') MH/s";else echo 'Benchmark:          ещё не начался';fi;echo
 gpu=$(nvidia-smi --query-gpu=temperature.gpu,utilization.gpu,clocks.current.sm,power.draw,power.limit,fan.speed --format=csv,noheader,nounits 2>/dev/null|head -1);echo 'GPU RTX 3080';echo '--------------------------------------------------------------------------------';echo "$gpu";echo
 echo 'ТАБЛИЦА ПРОФИЛЕЙ';echo '--------------------------------------------------------------------------------';printf '%-3s %-29s %-11s %-10s %-6s %-7s\n' '#' 'Профиль' 'Статус' 'MH/s' 'Regs' 'Stack';for ((i=0;i<TOTAL;i++));do p=${IDS[$i]};l=$(result "$p");if [[ -n $l ]];then ok=$(field "$l" valid||echo 0);if [[ $ok == 1 ]];then st=ГОТОВ;mh=$(field "$l" median_mhs||echo -);rg=$(field "$l" registers||echo -);sk=$(field "$l" stack||echo -);else st=ОШИБКА;mh=-;rg=-;sk=-;fi;elif [[ $p == "$current" && $state == РАБОТАЕТ ]];then st='В РАБОТЕ';mh=-;rg=-;sk=-;else st=ОЖИДАЕТ;mh=-;rg=-;sk=-;fi;printf '%-3d %-29s %-11s %-10s %-6s %-7s\n' "$((i+1))" "$p" "$st" "$mh" "$rg" "$sk";done;echo
 best=$(grep -a '^PROFILE_RESULT ' "$LOG"|grep ' valid=1 '|awk '{p="";h=0;m="";rg="";st="";md="";for(i=1;i<=NF;i++){split($i,a,"=");if(a[1]=="profile")p=a[2];else if(a[1]=="median_hps")h=a[2]+0;else if(a[1]=="median_mhs")m=a[2];else if(a[1]=="registers")rg=a[2];else if(a[1]=="stack")st=a[2];else if(a[1]=="mode")md=a[2]}if(h>b){b=h;bp=p;bm=m;br=rg;bs=st;bmd=md}}END{if(b)print bp"|"bm"|"b"|"br"|"bs"|"bmd}')
 sel=$(result selector-inline);selh=$(field "$sel" median_hps 2>/dev/null||echo 0);echo 'ЛУЧШИЙ РЕЗУЛЬТАТ';echo '--------------------------------------------------------------------------------';if [[ -n $best ]];then IFS='|' read -r bp bm bh br bs bmd<<<"$best";echo "Профиль:            $bp";echo "Результат:          $bm MH/s ($bh H/s)";echo "Режим:              $bmd";echo "Ресурсы:            $br регистров, stack $bs B";[[ $selh =~ ^[1-9][0-9]*$ ]]&&echo "К exact selector:   $(awk -v b="$bh" -v s="$selh" 'BEGIN{printf "%+.4f%%",(b/s-1)*100}')";echo "До 2 MH/s:          $(awk -v b="$bh" 'BEGIN{printf "%.4f%%",(2e6-b)/2e6*100}')";else echo 'Пока нет завершённых валидных профилей.';fi;echo
 if [[ $state == ЗАВЕРШЁН ]];then echo 'ИТОГ И ССЫЛКИ';echo '--------------------------------------------------------------------------------';grep -aE '^(profiles_|baseline_|selector_|best_|uplift_|target_|projected_|stress_gate|candidate_gate|ARCHIVE=|SHA256_FILE=|LOCAL_|PUBLIC_|DOWNLOAD_)' "$LOG"|tail -n80||true;echo;echo 'Панель остановлена: тест завершён.';break;fi
 if [[ $state == 'ОСТАНОВЛЕН / ПРОВЕРЬТЕ ЖУРНАЛ' ]];then echo 'ПОСЛЕДНИЕ СТРОКИ ЖУРНАЛА';echo '--------------------------------------------------------------------------------';tail -n50 "$LOG";break;fi
 echo "Журнал: $LOG";echo 'Ctrl+C закрывает только панель.';sleep "$REFRESH"
done
