#!/usr/bin/env bash
set -o pipefail
LOG="${1:-/root/v090-fullstack.log}"; REFRESH="${REFRESH:-10}"; SCREEN_NAME="${SCREEN_NAME:-v090-fullstack}"
IDS=(selector-combined-base hwfrac blake8 blake8-cv blake8-cv-inplace blake-direct-inplace const-cold ldg-cold blake8-cv-inplace-const blake8-cv-inplace-ldg hwfrac-blake8-cv-const blake-direct-inplace-const full-u2 full-u4 full-ftz full-vector full-expensive full-compiler-combo)
TOTAL="${#IDS[@]}"; TARGET=2000000
bar(){ local d="${1:-0}" t="${2:-1}" w="${3:-42}" f e; [[ "$d" =~ ^[0-9]+$ ]]||d=0; [[ "$t" =~ ^[1-9][0-9]*$ ]]||t=1; ((d>t))&&d=$t; f=$((d*w/t)); e=$((w-f)); printf '['; printf '%*s' "$f" ''|tr ' ' '#'; printf '%*s' "$e" ''|tr ' ' '-'; printf ']'; }
field(){ local l="${1:-}" k="${2:-}" x; for x in $l; do [[ "${x%%=*}" == "$k" ]]&&{ echo "${x#*=}"; return; }; done; }
result(){ grep -a '^PROFILE_RESULT ' "$LOG" 2>/dev/null|grep " profile=$1 "|tail -n1||true; }
while true; do
 printf '\033[H\033[2J'; echo '================================================================================'; echo ' PEPEPOW v0.9.0 — FULL-STACK CUDA OPTIMIZATION'; echo ' BLAKE3 stack pruning | exact selector | constant cache | compiler matrix'; echo '================================================================================'; echo
 if [[ ! -f "$LOG" ]]; then echo "Журнал ещё не создан: $LOG"; sleep "$REFRESH"; continue; fi
 done_n="$(grep -ac '^PROFILE_RESULT ' "$LOG" 2>/dev/null||true)"; ok="$(grep -a '^PROFILE_RESULT ' "$LOG" 2>/dev/null|grep -c ' valid=1 '||true)"; bad="$(grep -a '^PROFILE_RESULT ' "$LOG" 2>/dev/null|grep -c ' valid=0 '||true)"; current="$(grep -a '^PROFILE=' "$LOG" 2>/dev/null|tail -n1|cut -d= -f2-)"; status="$(grep -a '^STATUS=' "$LOG" 2>/dev/null|tail -n1|cut -d= -f2-)"; config="$(grep -a '^PROFILE_CONFIG ' "$LOG" 2>/dev/null|tail -n1)"; [[ -n "$current" ]]||current=инициализация; [[ -n "$status" ]]||status=ПОДГОТОВКА
 if screen -ls 2>/dev/null|grep -q "\.$SCREEN_NAME[[:space:]]"; then state=РАБОТАЕТ; elif grep -aq 'V0.9.0 FULL-STACK COMPLETE' "$LOG"; then state=ЗАВЕРШЁН; done_n=$TOTAL; else state='ОСТАНОВЛЕН / ПРОВЕРЬТЕ ЖУРНАЛ'; fi
 pct=$((done_n*100/TOTAL)); ((pct>100))&&pct=100
 echo 'ОБЩИЙ СТАТУС'; echo '--------------------------------------------------------------------------------'; echo "Состояние:          $state"; echo "Завершено:          $done_n из $TOTAL (валидных $ok, ошибок $bad)"; printf 'Общий прогресс:     '; bar "$done_n" "$TOTAL"; printf ' %3d%%\n' "$pct"; echo "Обновление:         каждые $REFRESH секунд"; echo
 echo 'ТЕКУЩИЙ ПРОФИЛЬ'; echo '--------------------------------------------------------------------------------'; echo "Профиль:            $current"; echo "Этап:               $status"; [[ -n "$config" ]]&&echo "Конфигурация:       ${config#PROFILE_CONFIG }"
 last="$(grep -a '^BENCH_RUN ' "$LOG" 2>/dev/null|grep " profile=$current "|tail -n1||true)"; if [[ -n "$last" ]]; then run="$(field "$last" run)"; h="$(field "$last" hps)"; echo "Benchmark:          $run"; [[ "$h" =~ ^[0-9]+$ ]]&&echo "Последний хеш:      $(awk -v x="$h" 'BEGIN{printf "%.6f",x/1e6}') MH/s ($h H/s)"; else echo 'Benchmark:          ещё не начался'; fi; echo
 echo 'GPU RTX 3080'; echo '--------------------------------------------------------------------------------'; gpu="$(nvidia-smi --query-gpu=temperature.gpu,utilization.gpu,clocks.current.sm,clocks.current.memory,power.draw,power.limit,fan.speed --format=csv,noheader,nounits 2>/dev/null|head -n1)"; [[ -n "$gpu" ]]&&echo "$gpu"||echo 'nvidia-smi недоступен'; echo
 echo 'ТАБЛИЦА ПРОФИЛЕЙ'; echo '--------------------------------------------------------------------------------'; printf '%-3s %-29s %-10s %-10s %-6s %-7s\n' '#' 'Профиль' 'Статус' 'MH/s' 'Regs' 'Stack'
 for ((i=0;i<TOTAL;i++)); do p="${IDS[$i]}"; l="$(result "$p")"; if [[ -n "$l" ]]; then v="$(field "$l" valid)"; if [[ "$v" == 1 ]]; then s=ГОТОВ; mh="$(field "$l" median_mhs)"; rg="$(field "$l" registers)"; st="$(field "$l" stack)"; else s=ОШИБКА; mh=-; rg=-; st=-; fi; elif [[ "$p" == "$current" && "$state" == РАБОТАЕТ ]]; then s='В РАБОТЕ'; mh=-; rg=-; st=-; else s=ОЖИДАЕТ; mh=-; rg=-; st=-; fi; printf '%-3d %-29s %-10s %-10s %-6s %-7s\n' "$((i+1))" "$p" "$s" "$mh" "$rg" "$st"; done; echo
 best="$(grep -a '^PROFILE_RESULT ' "$LOG" 2>/dev/null|grep ' valid=1 '|awk '{p="";h=0;m="";r="";s="";for(i=1;i<=NF;i++){split($i,a,"=");if(a[1]=="profile")p=a[2];else if(a[1]=="median_hps")h=a[2]+0;else if(a[1]=="median_mhs")m=a[2];else if(a[1]=="registers")r=a[2];else if(a[1]=="stack")s=a[2]}if(h>b){b=h;bp=p;bm=m;br=r;bs=s}}END{if(b>0)printf "%s|%s|%d|%s|%s",bp,bm,b,br,bs}')"; base_line="$(result selector-combined-base)"; base_h="$(field "$base_line" median_hps 2>/dev/null||echo 0)"
 echo 'ЛУЧШИЙ РЕЗУЛЬТАТ'; echo '--------------------------------------------------------------------------------'; if [[ -n "$best" ]]; then IFS='|' read -r bp bm bh br bs<<<"$best"; echo "Профиль:            $bp"; echo "Хешрейт:            $bm MH/s ($bh H/s)"; echo "Ресурсы:            $br регистров | stack $bs B"; [[ "$base_h" =~ ^[1-9][0-9]*$ ]]&&echo "К selector-combined: $(awk -v x="$bh" -v b="$base_h" 'BEGIN{printf "%+.4f%%",(x/b-1)*100}')"; echo "До 2 MH/s:          $(awk -v x="$bh" -v t="$TARGET" 'BEGIN{printf "%.4f%%",(t-x)/t*100}')"; else echo 'Пока нет валидных результатов.'; fi; echo
 if [[ "$state" == ЗАВЕРШЁН ]]; then echo 'ИТОГ И ССЫЛКИ'; echo '--------------------------------------------------------------------------------'; grep -aE '^(profiles_|baseline_|best_|uplift_|target_|projected_|stress_gate|sanitizer_gate|full_gate|TARGET_|ARCHIVE=|SHA256_FILE=|PUBLIC_|DOWNLOAD_)' "$LOG"|tail -n100||true; echo; break; fi
 if [[ "$state" == 'ОСТАНОВЛЕН / ПРОВЕРЬТЕ ЖУРНАЛ' ]]; then echo 'ПОСЛЕДНИЕ СТРОКИ ЖУРНАЛА'; echo '--------------------------------------------------------------------------------'; tail -n50 "$LOG"; break; fi
 echo "Журнал: $LOG"; echo "Ctrl+C закрывает только панель; тест продолжится в screen."; sleep "$REFRESH"
done
